/**
 * MCC reference lookup (Story 4.1 Task 5 — ENT-022).
 *
 * A pure function over a vendored, COMMITTED JSON table. The JSON is imported
 * directly (plain JSON import — NO `?raw`, NO fetch), so this module performs
 * ZERO runtime network: it is a synchronous, dependency-free map read.
 *
 * The table is generated by `tools/gen-mcc-reference.mjs` (manual; never run at
 * install/build time). See `mcc-reference.LICENSE.md` for attribution.
 */

import data from './mcc-reference.json';

/** Returned when `mcc` is null/undefined — stable, language-agnostic. */
const NULL_FALLBACK = '—';

// The JSON has a leading `_meta` provenance key alongside the "dddd" entries.
type MccEntry = { uk?: string; en?: string };
const table = data as Record<string, MccEntry | unknown>;

/** Zero-pads an MCC to a 4-digit "dddd" string. */
function pad4(mcc: number): string {
  return String(mcc).padStart(4, '0');
}

/**
 * Resolves a human-readable title for an MCC.
 *
 * - `mcc == null` → the stable null fallback (`'—'`).
 * - Known code with a title in `lang` → that title.
 * - Otherwise (absent code, or present without `lang`) → the bare "dddd" code.
 *
 * Pure: never touches the network; `_meta` is never treated as a code.
 */
export function mccTitle(mcc: number | null, lang: 'uk' | 'en'): string {
  if (mcc == null) return NULL_FALLBACK;

  const code = pad4(mcc);
  if (code === '_meta') return code; // defensive: never resolve the meta key
  const entry = table[code] as MccEntry | undefined;
  const title = entry?.[lang];
  return title ?? code;
}
