/**
 * Session registry — shared between the direct client and the worker host.
 *
 * Enforces the session lifecycle contract (founder refinement 1):
 *   - ≤1 active session at a time.
 *   - importStart while active → SessionAlreadyActiveError.
 *   - importAbort / completed importNext → frees the session from the registry.
 *   - Sessions die with the worker; after respawn, importStart is the only way forward.
 *
 * The registry holds the worker-side stage graph by sessionId. Session ids are
 * opaque strings generated by the engine's id generator.
 *
 * importGetRows windows: the registry stores the generated rows after importNext
 * so that importGetRows can serve windowed slices without re-running stage3.
 */

import { SessionAlreadyActiveError, SessionUnknownError } from '../../client/errors';
import type { ImportStatementStage2 } from '../importStatement/stage2/types';
import type { GenerateRowsResult } from '../importStatement/stage3/types';

// ── Session state ─────────────────────────────────────────────────────────────

/**
 * An active import session entry.
 * stage2 is the live RxJS/column-graph; generatedRows is set after importNext.
 */
export interface SessionEntry {
  readonly sessionId: string;
  readonly stage2: ImportStatementStage2;
  generatedRows: GenerateRowsResult | null;
}

// ── SessionRegistry ───────────────────────────────────────────────────────────

/**
 * In-process session registry.
 *
 * Supports N sessions in tests (the spec helpers create multiple sessions);
 * enforces the product constraint of ≤1 active session via the activeSessionId
 * sentinel.
 *
 * Create one instance per worker-host / direct-client and share it across all
 * method dispatch calls.
 */
export class SessionRegistry {
  private readonly _sessions = new Map<string, SessionEntry>();
  private _activeSessionId: string | null = null;

  /** Number of currently tracked sessions (includes the active one). */
  get size(): number {
    return this._sessions.size;
  }

  /** The id of the currently active session, or null when idle. */
  get activeSessionId(): string | null {
    return this._activeSessionId;
  }

  /**
   * Register a new session.
   *
   * Throws SessionAlreadyActiveError if another session is already active.
   * (The caller must importAbort the existing session first.)
   */
  register(sessionId: string, stage2: ImportStatementStage2): SessionEntry {
    if (this._activeSessionId !== null) {
      throw new SessionAlreadyActiveError(this._activeSessionId);
    }
    const entry: SessionEntry = { sessionId, stage2, generatedRows: null };
    this._sessions.set(sessionId, entry);
    this._activeSessionId = sessionId;
    return entry;
  }

  /**
   * Retrieve a session by id.
   *
   * Throws SessionUnknownError if the id is not found.
   */
  get(sessionId: string): SessionEntry {
    const entry = this._sessions.get(sessionId);
    if (!entry) {
      throw new SessionUnknownError(sessionId);
    }
    return entry;
  }

  /**
   * Check whether a session exists.
   */
  has(sessionId: string): boolean {
    return this._sessions.has(sessionId);
  }

  /**
   * Free a session from the registry.
   * Clears the activeSessionId sentinel when the freed session was the active one.
   * No-op if the session is already absent (idempotent).
   */
  free(sessionId: string): void {
    this._sessions.delete(sessionId);
    if (this._activeSessionId === sessionId) {
      this._activeSessionId = null;
    }
  }

  /**
   * Destroy all sessions (called when the worker dies / is restarted).
   * Clears everything so the next importStart starts fresh.
   */
  clear(): void {
    this._sessions.clear();
    this._activeSessionId = null;
  }
}
